name: Build and Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - s3-to-storybook

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.19.0

      - name: Install Yarn
        uses: borales/actions-yarn@v4
        with:
          cmd: install 

      - name: Install Ruby and Gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.2
          bundler-cache: true
      
      - name: Install Bundler
        run: gem install bundler
        
      - name: Install Yarn Dependencies
        run: |
          cd vets-design-system-documentation
          bundle install
          yarn install

      - name: Build Jekyll Site
        run: |
          cd vets-design-system-documentation
          ls -la
          yarn run build
          bundle exec jekyll build --destination ./_site 

      - name: Debug GitHub Pages Deployment
        run: |
          echo "Listing deployment files..."
          ls -la vets-design-system-documentation/_site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './vets-design-system-documentation/_site'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
