name: Build and Deploy Jekyll to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - s3-to-storybook

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.19.0

      - name: Use Correct Yarn Version
        run: |
          corepack enable
          corepack prepare yarn@1.22.19 --activate
          yarn --version
          
      - name: Install Ruby and Gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.2
          bundler-cache: true

      - name: Install Bundler
        run: gem install bundler

      - name: Install Yarn and Ruby Dependencies
        run: |
          cd vets-design-system-documentation
          bundle install
          yarn install

      - name: Build Jekyll Site
        run: |
          cd vets-design-system-documentation
          yarn run build
          bundle exec jekyll build --destination ./_site 

      - name: Debug Deployment Files
        run: |
          echo "Checking output directory..."
          ls -la vets-design-system-documentation/_site

      - name: Upload GitHub Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './vets-design-system-documentation/_site'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
